from base.com.controller import assignment_controller
from base.com.controller import degree_controller
from base.com.controller import department_controller
from base.com.controller import exam_controller
from base.com.controller import faculty_controller
from base.com.controller import lecture_controller
from base.com.controller import login_controller
from base.com.controller import semester_controller
from base.com.controller import student_controller
from base.com.controller import subject_controller